-- inventory-service: initial schema.
-- Hibernate only validates this schema (ddl-auto: validate); every change needs a new V<n>__*.sql.
-- Unique constraints use the names Hibernate generated when it managed the schema (ddl-auto: update),
-- so databases created before Flyway and databases created by Flyway are identical.

CREATE TABLE inventories (
    id                 UUID         NOT NULL,
    product_id         UUID         NOT NULL,
    sku                VARCHAR(255) NOT NULL,
    total_quantity     INTEGER      NOT NULL,
    reserved_quantity  INTEGER      NOT NULL,
    available_quantity INTEGER      NOT NULL,
    status             VARCHAR(255) NOT NULL CHECK (status IN ('ACTIVE', 'LOW_STOCK', 'OUT_OF_STOCK', 'DISCONTINUED', 'UNKNOWN')),
    created_at         TIMESTAMP(6) WITH TIME ZONE,
    updated_at         TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT uk3bms153u88bt0daekfy4qpj6k UNIQUE (product_id),
    CONSTRAINT uk2go4auy3t9yxvuswnvpbow2p7 UNIQUE (sku)
);

-- One row per order this service has seen; the unique order_id makes reservations idempotent.
CREATE TABLE stock_reservations (
    id         UUID         NOT NULL,
    order_id   BIGINT       NOT NULL,
    product_id UUID,
    quantity   INTEGER      NOT NULL,
    status     VARCHAR(255) NOT NULL CHECK (status IN ('RESERVED', 'REJECTED', 'RELEASED', 'CANCELLED')),
    reason     VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT uk629g7ucwoefkvapwlhk3s7bwi UNIQUE (order_id)
);

-- Idempotent consumers: one row per (listener, event) handled.
CREATE TABLE processed_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    consumer     VARCHAR(255) NOT NULL,
    event_id     VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_processed_events_consumer_event UNIQUE (consumer, event_id)
);
