-- order-service: initial schema.
-- Hibernate only validates this schema (ddl-auto: validate); every change needs a new V<n>__*.sql.

CREATE TABLE orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id    UUID,
    product_name  VARCHAR(255),
    quantity      INTEGER,
    price         FLOAT(53),
    status        VARCHAR(255) CHECK (status IN ('CREATED', 'CONFIRMED', 'REJECTED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    status_reason VARCHAR(255),
    created_at    TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE audit_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id     BIGINT,
    product_name VARCHAR(255),
    status       VARCHAR(255),
    event_time   TIMESTAMP(6),
    PRIMARY KEY (id)
);

-- Transactional outbox: events are written here in the same transaction as the order change,
-- and OutboxRelay publishes them to Kafka.
CREATE TABLE outbox_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    aggregate_type VARCHAR(255)  NOT NULL,
    aggregate_id   VARCHAR(255)  NOT NULL,
    event_type     VARCHAR(255)  NOT NULL,
    topic          VARCHAR(255)  NOT NULL,
    message_key    VARCHAR(255)  NOT NULL,
    payload        TEXT          NOT NULL,
    created_at     TIMESTAMP(6)  NOT NULL,
    published_at   TIMESTAMP(6),
    attempts       INTEGER       NOT NULL,
    last_error     VARCHAR(1000),
    PRIMARY KEY (id)
);

-- The relay's query: oldest unpublished events first.
CREATE INDEX idx_outbox_events_unpublished ON outbox_events (published_at, id);

-- Idempotent consumers: one row per (listener, event) handled.
CREATE TABLE processed_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    consumer     VARCHAR(255) NOT NULL,
    event_id     VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_processed_events_consumer_event UNIQUE (consumer, event_id)
);
