package com.arpitha.common.event;

public enum EventType {
    ORDER_CREATED,
    ORDER_UPDATED,
    ORDER_CANCELLED,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    INVENTORY_RESERVED,
    INVENTORY_RESERVATION_FAILED
}
